matrix:
  include:
  - os: osx
    osx_image: xcode9.2
    language: node_js
    node_js: '9'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    services: docker
    language: generic
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
    export PATH="/tmp/git-lfs:$PATH"
  fi
before_script:
- git lfs pull
script:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    docker run --rm \
      --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
      -v ${PWD}:/project \
      -v ~/.cache/electron:/root/.cache/electron \
      -v ~/.cache/electron-builder:/root/.cache/electron-builder \
      electronuserland/builder:wine \
      /bin/bash -c "npm run build:prod && npm run release:linux && npm run release:win"
  else
    npm run build:prod && npm run release:mac
  fi
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
deploy:
  provider: releases
  api_key:
    secure: y7QgS/+25Fv+gsb67zk/bkp4rj9zxcg5ywfoyrISCTCeUGuYZN6JO/HMU2LyqXUeJFpzSVX36mfGjM4h1fN6RRbFxYUlLWcJhE6CkQosVDDk1I5u8yUgOlyOHVR73fgFu358NFdUuRgf66Hc1q/MTSlmvjR40FfIcmUB7/Tcs7WXHE9qDGgFFDgZWuVRytxopUn+LjSV46oESEGumQjPgNmeLrUzCgTZ9GJMDt/E8AX2LU4QFd21mtzkZ7TUHW2qAzLvUCLckceNY8fS4dr/Kb6Yw68ze3XlCDGzJtqsNFheRfxKCKbHT18GqQcJ3KA3f1jk68hCXgQ5ptDtYrvhYfPjVuEGQbp3+p+TuOvZHYg2cdc/OzLiq3R6rbKtlIT7vEuRBL5co1rIgNc1ZQhdwnAnMP7ZwRQJ5sPcNYc+M/Fn9hl+dTUge4K060yILXd1STvB7/Mf9BbcbyY9RWaIcY5v34v12Fy+Ew8wkIbpfeBUhdOQoGBIAyX9UKlnF9iE9UPkbZqs04ER0/9Y6nangon4MmCJxwGSozohcm76GroI+28PA5qsrnlAi2YA3uGI8vyCLrZKfkY1laGWQ4WKnIdau6KuTroHxQBoSyVTyltqovWRr/nqA2lzegzQPA7LHS/MZhjg8dSZtlUTGbd1n2/RgxyB2UZUtE/AQYTPOtY=
  skip_cleanup: true
  file_glob: true
  file:
    - releases/Lindo-*.dmg
    - releases/Lindo-*.zip
    - releases/lindo-*.tar.gz
    - releases/Lindo*.exe
  on:
    tags: true
    repo: prixe/lindo
